# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainActivity.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 900)
        Form.setMinimumSize(QtCore.QSize(1600, 900))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1_DBConnect = QtWidgets.QWidget()
        self.page_1_DBConnect.setObjectName("page_1_DBConnect")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_1_DBConnect)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.page_1_DBConnect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_3.sizePolicy().hasHeightForWidth())
        self.treeWidget_3.setSizePolicy(sizePolicy)
        self.treeWidget_3.setObjectName("treeWidget_3")
        font = QtGui.QFont()
        font.setPointSize(1)
        self.treeWidget_3.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        item_0.setFont(0, font)
        self.gridLayout_3.addWidget(self.treeWidget_3, 0, 0, 1, 1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_1_DBConnect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_7)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(240, 240, 501, 321))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_68 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_7.addWidget(self.label_68)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.lineEdit_1_localHost = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_1_localHost.setObjectName("lineEdit_1_localHost")
        self.horizontalLayout_7.addWidget(self.lineEdit_1_localHost)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_76 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_8.addWidget(self.label_76)
        spacerItem1 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.lineEdit_1_localDBName = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_1_localDBName.setObjectName("lineEdit_1_localDBName")
        self.horizontalLayout_8.addWidget(self.lineEdit_1_localDBName)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_69 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_10.addWidget(self.label_69)
        spacerItem2 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.lineEdit_1_localPort = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_1_localPort.setObjectName("lineEdit_1_localPort")
        self.horizontalLayout_10.addWidget(self.lineEdit_1_localPort)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_70 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_11.addWidget(self.label_70)
        spacerItem3 = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.lineEdit_1_localAccount = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_1_localAccount.setObjectName("lineEdit_1_localAccount")
        self.horizontalLayout_11.addWidget(self.lineEdit_1_localAccount)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_71 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_12.addWidget(self.label_71)
        spacerItem4 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.lineEdit_1_localPwd = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineEdit_1_localPwd.setObjectName("lineEdit_1_localPwd")
        self.horizontalLayout_12.addWidget(self.lineEdit_1_localPwd)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_2.addWidget(self.page_8)
        self.gridLayout_3.addWidget(self.stackedWidget_2, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_1_DBConnect)
        self.page_1_ConnnectionMethod = QtWidgets.QWidget()
        self.page_1_ConnnectionMethod.setObjectName("page_1_ConnnectionMethod")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.page_1_ConnnectionMethod)
        self.treeWidget_2.setGeometry(QtCore.QRect(520, 40, 210, 806))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_2.sizePolicy().hasHeightForWidth())
        self.treeWidget_2.setSizePolicy(sizePolicy)
        self.treeWidget_2.setObjectName("treeWidget_2")
        font = QtGui.QFont()
        font.setPointSize(1)
        self.treeWidget_2.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        item_0.setFont(0, font)
        self.stackedWidget.addWidget(self.page_1_ConnnectionMethod)
        self.page_1_About = QtWidgets.QWidget()
        self.page_1_About.setObjectName("page_1_About")
        self.pushButton = QtWidgets.QPushButton(self.page_1_About)
        self.pushButton.setGeometry(QtCore.QRect(680, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_1_About)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setPointSize(3)
        self.treeWidget.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setToolTip(0, "")
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/bullet_connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/arrow_switch_bluegreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/stock_connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon2)
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_3.headerItem().setText(0, _translate("Form", "___"))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, _translate("Form", "云数据库"))
        self.treeWidget_3.topLevelItem(1).setText(0, _translate("Form", "本地数据库"))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_68.setText(_translate("Form", "主机名或IP地址:"))
        self.lineEdit_1_localHost.setText(_translate("Form", "localhost"))
        self.label_76.setText(_translate("Form", "数据库名称:"))
        self.lineEdit_1_localDBName.setText(_translate("Form", "bjpowernode"))
        self.label_69.setText(_translate("Form", "端口:"))
        self.lineEdit_1_localPort.setText(_translate("Form", "3306"))
        self.label_70.setText(_translate("Form", "用户名:"))
        self.lineEdit_1_localAccount.setText(_translate("Form", "root"))
        self.label_71.setText(_translate("Form", "密码:"))
        self.treeWidget_2.headerItem().setText(0, _translate("Form", "___"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("Form", "云数据库"))
        self.treeWidget_2.topLevelItem(1).setText(0, _translate("Form", "本地数据库"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "_________"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "数据库登陆"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "通信方式"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "关于"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

